---
link: /about/committee
slug: committee
title: Committee Members and contacts
---

| Club Role                     | Name               | Phone         | Email Address                                                      |
| ----------------------------  | -----------------  | ------------  | -----------------------------------------------------------------  |
| President                     | Sue Cornish        | 0401 363 647  | [president@hprtc.org.au](mailto:president@hprtc.org.au)            |
| Vice President                | Alex Chen          |               | [vice.president@hprtc.org.au](mailto:vice.president@hprtc.org.au)  |
| Secretary                     | Diana Baxter       |               | [secretary@hprtc.org.au](mailto:secretary@hprtc.org.au)            |
| Treasurer                     | Devina Ditchfield  | 0414 773 093  | [treasurer@hprtc.org.au](mailto:treasurer@hprtc.org.au)            |
| Junior Convenor               | James Ni           |               | [juniors@hprtc.org.au](mailto:juniors@hprtc.org.au)                |
| Maintenance                   | Mal McDonald       | 0407 303 407  | [maintenance@hprtc.org.au](mailto:maintenance@hprtc.org.au)        |
| Membership and Key Registrar  | Jeremy Knapp       |               | [member-admin@hprtc.org.au](mailto:member-admin@hprtc.org.au)      |
| Night Rep                     | Edda Zhou          | 0475 429 585  | [night@hprtc.org.au](mailto:night@hprtc.org.au)                    |
| Night Rep                     | James Wotherspoon  | 0407 357 318  | [night1@hprtc.org.au](mailto:night1@hprtc.org.au)                  |
| Mid Week Ladies Rep           | Ros Brereton       | 9729 3259     | [ladies@hprtc.org.au](mailto:ladies@hprtc.org.au)                  |
| Head Coach                    | Ben Longridge      | 0413 619 028  | [coach@hprtc.org.au](mailto:coach@hprtc.org.au)                    |
| General Committee             | Don Hamilton       | 0414 538 336  |                                                                    |
| General Committee             | Chris Wishart      | 0401 722 040  |                                                                    |
| Monday Men's Social           | Don Hamilton       | 0414 538 336  |                                                                    |
| Friday Ladies' Social         | Dianne Nemeth      | 0418 922 954  |                                                                    |
| Friday Ladies' Social         | Jill Cowie         | 0413 894 215  |                                                                    |
