---
link: /about/conduct
slug: conduct
title: Code of conduct
---

Remember that children play tennis for fun. To ensure a safe and enjoyable environment, all players, parents/guardians and spectators are expected to follow these guidelines:

 * Encourage all players to participate. Play for the “fun of it”.
 * Respect the rights and dignity of every person regardless of their gender, ability, cultural background or religion.
 * Co-operate, support and encourage your team mates. Your team&#39;s performance will benefit; so will you.
 * Remember that players learn best from example. Applaud good play and effort by both teams.
 * Encourage players to always participate according to the rules and to respect decisions.
 * Demonstrate appropriate social behaviour. Harassment, verbal abuse or use of foul language to any person, including yourself, will not be tolerated.
 * Recognise the value and importance of coaches and conveners. The convener’s role is to help organise and oversee the running of all matches. The convener or coach can also help if you have rule or score questions, or need extra support. If you disagree with a decision, raise the issue through the appropriate channel.
 * Equipment and the court are to be treated respectfully. Take care to not throw your racquet, damage the playing surface, the net or fences. Remember to bag courts after use, and to leave courts neat and tidy.
 * Respect tennis matches on other courts. Take care to not interrupt play or distract players.

### Commitment to Child Safety

 * HE Parker Reserve Tennis club is committed to child safety and the welfare of all children at the club is our priority. This includes both members, visitors and siblings.
 * Child abuse can take a broad range of forms including physical abuse, sexual abuse, emotional or psychological abuse and neglect.
 * The club encourages children to express their views about their safety.
 * All members of the club have a role and responsibility in ensuring the safety of all children attending the club. This can be achieved by:

   - Acting in a manner that enhances the safety of all children;
   - Appropriately act on any concerns raised;
   - Understand and follow all applicable laws (including reporting and management of child safety);
   - Any concerns can be directed to any member of the tennis committee for further attention.

