---
link: /about/legal
slug: legal
title: Terms and Conditions
---

Heathmont Parker Reserve Tennis Club’s Website (“Website”) is owned and operated by Heathmont Parker Reserve Tennis Club and is hosted on a server in the State of Victoria. The use of the Website and any material or information contained in the Website (“Material”) is governed by the law of the State of Victoria, Australia.

By using or accessing any part of the Website or the Material you agree to be bound by these terms

## Changes to the Website and Material

The Website and the Material are subject to change at any time without notice and may contain errors. Heathmont Parker Reserve Tennis Club makes no warranties or representations as to the quality, accuracy, completeness or suitability for any purpose of the Website or the Material.

To the extent permitted by law Heathmont Parker Reserve Tennis Club excludes all warranties, whether express or implied, in relation to the Website, the Material, all links to or from the Website, and the services accessible thereby.

## Links

The Website may contain links to other Websites. Heathmont Parker Reserve Tennis Club provides those links as a ready reference for searching the internet and not as an endorsement of those Websites, their operators or the goods and services that they describe. Heathmont Parker Reserve Tennis Club is not responsible for and will not be liable in respect of the content or operation of those Websites or any of the goods and services that they describe.

You are not permitted to link to or frame the Website without Heathmont Parker Reserve Tennis Club’s express written permission.

## Copyright&nbsp;

Copyright in the Website, the Material and all components of it is owned or licensed by Heathmont Parker Reserve Tennis Club unless otherwise indicated. You must not copy, modify or transmit any of the Material except as permitted below.

You are permitted to save, print and reproduce pages from the Website (but not excerpts from pages) solely for your personal information, research or study, but you must not modify those copies and you must include the Heathmont Parker Reserve Tennis Club copyright notice “© Heathmont Parker Reserve Tennis Club” on all copies.

## Trade Marks

The Website contains trade marks which may be registered or otherwise protected by law. These include the Heathmont Parker Reserve Tennis Club logo and the logos of various sponsors. You are not permitted to use these trade marks.

## Liability

Subject to any applicable law which cannot be excluded, Heathmont Parker Reserve Tennis Club’s liability in respect of the Website and the Material is limited to resupplying the relevant Material or the reasonable cost of resupplying the relevant Material, whichever Heathmont Parker Reserve Tennis Club sees fit to provide.

Heathmont Parker Reserve Tennis Club will not in any case be liable for any direct or indirect lost profit or incidental, consequential or special damages arising out of or in connection with the Website or the Material.

## Privacy

Heathmont Parker Reserve Tennis Club is committed to the protection of your personal information in accordance with the National Privacy Principles set out in the Privacy Act 1988 (Cth).

In general, you can view the Heathmont Parker Reserve Tennis Club website without revealing any information about yourself. However, there are times Heathmont Parker Reserve Tennis Club may seek and collect information from you (for example, when you subscribe to our e-newsletter: The Net Post).This Heathmont Parker Reserve Tennis Club Privacy Policy tells you about your privacy and describes the manner in which Heathmont Parker Reserve Tennis Club collects, holds and uses personal information collected through our website. If you wish to make any inquiries regarding this Heathmont Parker Reserve Tennis Club Privacy Policy, you should contact Heathmont Parker Reserve Tennis Club’s secretary by email at the following address [secretary@hprtc.org.au](mailto:secretary@hprtc.org.au)

Heathmont Parker Reserve Tennis Club may, from time to time, review and update this Heathmont Parker Reserve Tennis Club Website Privacy Policy to take account new laws and technology. All personal information held by Heathmont Parker Reserve Tennis Club will be governed by its most recent policy, posted on the Website.

**1. What is “Personal Information”**

1.1 “Personal information” is any information or opinion (recorded in any form) about a person, whether true or not, from which that person may be identified.

1.2 Heathmont Parker Reserve Tennis Club collects personal information from its users via the Heathmont Parker Reserve Tennis Club website (Website) or when you email us or contact us by telephone or mail.

**2. Information collected via Heathmont Parker Reserve Tennis Club Website**

2.1 Heathmont Parker Reserve Tennis Club will not collect any personal information about visitors to the Website except when they knowingly provide it or as otherwise described below. For example, Heathmont Parker Reserve Tennis Club will collect personal information from users to its Website when they register to receive e-newsletters, enter competitions or surveys.

2.2 When you visit and browse the Website, Heathmont Parker Reserve Tennis Club’s Website host will collect personal information for statistical, reporting and maintenance purposes.

2.3 This information will not be used to identify you and may include:

  * the number of users visiting the Website and the number of pages viewed;
  * the date, time and duration of a visit; or
  * the path taken though the Website.

2.4 Heathmont Parker Reserve Tennis Club’s Website host uses this information to administer and improve the performance of the Website.

### Cookies

2.5 Cookies are small text files that are transferred to a user’s computer hard drive by a website for the purpose of storing information about a user’s identity, browser type or website visiting patterns.

2.6 If you access the Website, a cookie is downloaded onto your computer’s hard drive when you first log onto the Website and it is automatically deleted from your hard drive after a period of thirty days.

### Web Beacons

2.7 Web beacons are images that originate from a third party site to track visitor activities. Heathmont Parker Reserve Tennis Club does not currently use web beacons to track the visiting patterns of individuals accessing its Website.

**3. What information Heathmont Parker Reserve Tennis Club collects about you**

3.1 Heathmont Parker Reserve Tennis Club collects or may collect the following kinds of information about users:

  * ‘contact information’. This may include an email address where Heathmont Parker Reserve Tennis Club can contact you. It may also include your name, mobile phone number, other phone numbers or address details.
  * Communications (by email or other means, which pass through the Heathmont Parker Reserve Tennis Club systems) between yourself and Heathmont Parker Reserve Tennis Club.
  * Other personal information provided voluntarily by you. This could be in response to surveys, contests or online activities.
  * Non-personally identifiable information, such as your IP address, browser type, pages visited etc. None of this information identifies you personally.

**4. How Heathmont Parker Reserve Tennis Club uses the personal information it collect about you**

4.1 Heathmont Parker Reserve Tennis Club uses the information it collects from you for the primary purpose for which it is collected and for such other secondary purposes that are related to the primary purpose of collection. Heathmont Parker Reserve Tennis Club generally uses personal information to:

  * Provide you with products or services you have requested.
  * Direct marketing in relation to promotional activities where it is impracticable for Heathmont Parker Reserve Tennis Club to obtain your prior written consent. However, when Heathmont Parker Reserve Tennis Club does this, we will provide an express option for you to decline receiving any further marketing communications from Heathmont Parker Reserve Tennis Club, via an opt out mechanism. Heathmont Parker Reserve Tennis Club will only send you emails if you have elected to receive such emails in response to an email we have received from you.

**5. Who we disclose your personal information to**

5.1 Heathmont Parker Reserve Tennis Club does not disclose your information to its advertising and marketing agents. If you do not wish to receive promotional information, you can contact Heathmont Parker Reserve Tennis Club’s Privacy Officer at any stage in the future so that your name can be removed from its marketing lists.

5.2 Heathmont Parker Reserve Tennis Club may also disclose your personal information to its Website host and technology service providers in certain limited circumstances, for example, when the Website experiences a technical problem, to ensure that it operates in an effective and secure manner.

5.3 Otherwise, Heathmont Parker Reserve Tennis Club will not disclose any of your personal information to any other organisation, other than Tennis Victoria, unless the disclosure is required by law or is otherwise permitted by the National Privacy Principles.

**6. Your consent**

6.1 Heathmont Parker Reserve Tennis Club will only collect and use personal information as described above or otherwise with your consent and only within the limits of this Heathmont Parker Reserve Tennis Club Website Privacy Policy.

6.2 If you choose not to provide your personal information to Heathmont Parker Reserve Tennis Club for the purposes set out in this Heathmont Parker Reserve Tennis Club Website Privacy Policy, the only negative consequence for you will be that we will not be able to provide you with the requested product or service.

**7. Updating, storage and security of personal information held by Heathmont Parker Reserve Tennis Club**

7.1 Heathmont Parker Reserve Tennis Club aims to keep your personal information secure and up to date. Any personal information that is collected via the Website or which is held on Heathmont Parker Reserve Tennis Club’s computer systems is protected by safeguards including physical, technical (firewalls, SSL encryptions etc) and procedural methods.

7.2 Heathmont Parker Reserve Tennis Club does not collect sensitive or financial information about its users via the Website.

7.3 Personal information that is held by Heathmont Parker Reserve Tennis Club in hard copy is stored securely on its premises and is only disclosed or used for the purposes described in this Heathmont Parker Reserve Tennis Club Website Privacy Policy.

7.4 You can update your contact and profile information at any time by logging onto the Website and following the appropriate links.

**8. Finding out what personal information Heathmont Parker Reserve Tennis Club holds about you**

8.1 You are entitled to access personal information that Heathmont Parker Reserve Tennis Club holds about you. If you request access to your personal information, we will grant your request unless providing you with access would unreasonably impact upon the privacy of others or is not otherwise permitted under the National Privacy Principles. If Heathmont Parker Reserve Tennis Club refuses your request to access your personal information, it will provide you with reasons for our refusal.

8.2 A request for access can be done in any of the following ways:

email: [secretary@hprtc.org.au](mailto:secretary@hprtc.org.au)

write to: Secretary, Heathmont Parker Reserve Tennis Club, PO Box 695, Heathmont Vic 3135.

**9. What to do if you have a question, problem or complaint about our use of your personal information**

If you feel that your privacy has not been respected or that Heathmont Parker Reserve Tennis Club has conducted itself inconsistently with this Heathmont Parker Reserve Tennis Club Website Privacy Policy in respect of your personal information, please contact Heathmont Parker Reserve Tennis Club and ask for the Secretary (contact details above).


